// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	request "github.com/mattermost/mattermost/server/public/shared/request"
	mock "github.com/stretchr/testify/mock"
)

// AccessControlTemporaryAccessStore is an autogenerated mock type for the AccessControlTemporaryAccessStore type
type AccessControlTemporaryAccessStore struct {
	mock.Mock
}

func (_m *AccessControlTemporaryAccessStore) DeleteExpiredBatch(rctx request.CTX, now int64, limit int) (int64, error) {
	ret := _m.Called(rctx, now, limit)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, int64, int) int64); ok {
		r0 = rf(rctx, now, limit)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if rf, ok := ret.Get(1).(func(request.CTX, int64, int) error); ok {
		r1 = rf(rctx, now, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *AccessControlTemporaryAccessStore) DeleteByIDs(rctx request.CTX, ids []string) (int64, error) {
	ret := _m.Called(rctx, ids)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, []string) int64); ok {
		r0 = rf(rctx, ids)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if rf, ok := ret.Get(1).(func(request.CTX, []string) error); ok {
		r1 = rf(rctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *AccessControlTemporaryAccessStore) GetExpiredBatch(rctx request.CTX, now int64, limit int) ([]*model.AccessControlTemporaryAccess, error) {
	ret := _m.Called(rctx, now, limit)

	var r0 []*model.AccessControlTemporaryAccess
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, int64, int) []*model.AccessControlTemporaryAccess); ok {
		r0 = rf(rctx, now, limit)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]*model.AccessControlTemporaryAccess)
	}
	if rf, ok := ret.Get(1).(func(request.CTX, int64, int) error); ok {
		r1 = rf(rctx, now, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *AccessControlTemporaryAccessStore) Get(rctx request.CTX, id string) (*model.AccessControlTemporaryAccess, error) {
	ret := _m.Called(rctx, id)

	var r0 *model.AccessControlTemporaryAccess
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, string) *model.AccessControlTemporaryAccess); ok {
		r0 = rf(rctx, id)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*model.AccessControlTemporaryAccess)
	}
	if rf, ok := ret.Get(1).(func(request.CTX, string) error); ok {
		r1 = rf(rctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *AccessControlTemporaryAccessStore) HasActive(rctx request.CTX, check model.AccessControlTemporaryAccessActiveCheck) (bool, error) {
	ret := _m.Called(rctx, check)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, model.AccessControlTemporaryAccessActiveCheck) bool); ok {
		r0 = rf(rctx, check)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if rf, ok := ret.Get(1).(func(request.CTX, model.AccessControlTemporaryAccessActiveCheck) error); ok {
		r1 = rf(rctx, check)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *AccessControlTemporaryAccessStore) MarkAccepted(rctx request.CTX, id string, acceptedAt int64, joinedAt int64, membershipCreated bool) (*model.AccessControlTemporaryAccess, error) {
	ret := _m.Called(rctx, id, acceptedAt, joinedAt, membershipCreated)

	var r0 *model.AccessControlTemporaryAccess
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, string, int64, int64, bool) *model.AccessControlTemporaryAccess); ok {
		r0 = rf(rctx, id, acceptedAt, joinedAt, membershipCreated)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*model.AccessControlTemporaryAccess)
	}
	if rf, ok := ret.Get(1).(func(request.CTX, string, int64, int64, bool) error); ok {
		r1 = rf(rctx, id, acceptedAt, joinedAt, membershipCreated)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *AccessControlTemporaryAccessStore) MarkJoined(rctx request.CTX, id string, joinedAt int64, membershipCreated bool, teamMembershipCreated bool) (*model.AccessControlTemporaryAccess, error) {
	ret := _m.Called(rctx, id, joinedAt, membershipCreated, teamMembershipCreated)

	var r0 *model.AccessControlTemporaryAccess
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, string, int64, bool, bool) *model.AccessControlTemporaryAccess); ok {
		r0 = rf(rctx, id, joinedAt, membershipCreated, teamMembershipCreated)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*model.AccessControlTemporaryAccess)
	}
	if rf, ok := ret.Get(1).(func(request.CTX, string, int64, bool, bool) error); ok {
		r1 = rf(rctx, id, joinedAt, membershipCreated, teamMembershipCreated)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *AccessControlTemporaryAccessStore) Revoke(rctx request.CTX, id string, deleteAt int64, deletedBy string) (*model.AccessControlTemporaryAccess, error) {
	ret := _m.Called(rctx, id, deleteAt, deletedBy)

	var r0 *model.AccessControlTemporaryAccess
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, string, int64, string) *model.AccessControlTemporaryAccess); ok {
		r0 = rf(rctx, id, deleteAt, deletedBy)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*model.AccessControlTemporaryAccess)
	}
	if rf, ok := ret.Get(1).(func(request.CTX, string, int64, string) error); ok {
		r1 = rf(rctx, id, deleteAt, deletedBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *AccessControlTemporaryAccessStore) Save(rctx request.CTX, temporaryAccesses []*model.AccessControlTemporaryAccess) ([]*model.AccessControlTemporaryAccess, error) {
	ret := _m.Called(rctx, temporaryAccesses)

	var r0 []*model.AccessControlTemporaryAccess
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, []*model.AccessControlTemporaryAccess) []*model.AccessControlTemporaryAccess); ok {
		r0 = rf(rctx, temporaryAccesses)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]*model.AccessControlTemporaryAccess)
	}
	if rf, ok := ret.Get(1).(func(request.CTX, []*model.AccessControlTemporaryAccess) error); ok {
		r1 = rf(rctx, temporaryAccesses)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *AccessControlTemporaryAccessStore) Search(rctx request.CTX, opts model.AccessControlTemporaryAccessSearch) ([]*model.AccessControlTemporaryAccess, int64, error) {
	ret := _m.Called(rctx, opts)

	var r0 []*model.AccessControlTemporaryAccess
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(request.CTX, model.AccessControlTemporaryAccessSearch) []*model.AccessControlTemporaryAccess); ok {
		r0 = rf(rctx, opts)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]*model.AccessControlTemporaryAccess)
	}
	if rf, ok := ret.Get(1).(func(request.CTX, model.AccessControlTemporaryAccessSearch) int64); ok {
		r1 = rf(rctx, opts)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if rf, ok := ret.Get(2).(func(request.CTX, model.AccessControlTemporaryAccessSearch) error); ok {
		r2 = rf(rctx, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
