// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	request "github.com/mattermost/mattermost/server/public/shared/request"
	mock "github.com/stretchr/testify/mock"
)

// AccessControlBypassStore is an autogenerated mock type for the AccessControlBypassStore type
type AccessControlBypassStore struct {
	mock.Mock
}

func (_m *AccessControlBypassStore) DeleteExpiredBatch(rctx request.CTX, now int64, limit int) (int64, error) {
	ret := _m.Called(rctx, now, limit)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, int64, int) int64); ok {
		r0 = rf(rctx, now, limit)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if rf, ok := ret.Get(1).(func(request.CTX, int64, int) error); ok {
		r1 = rf(rctx, now, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *AccessControlBypassStore) DeleteByIDs(rctx request.CTX, ids []string) (int64, error) {
	ret := _m.Called(rctx, ids)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, []string) int64); ok {
		r0 = rf(rctx, ids)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if rf, ok := ret.Get(1).(func(request.CTX, []string) error); ok {
		r1 = rf(rctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *AccessControlBypassStore) GetExpiredBatch(rctx request.CTX, now int64, limit int) ([]*model.AccessControlBypass, error) {
	ret := _m.Called(rctx, now, limit)

	var r0 []*model.AccessControlBypass
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, int64, int) []*model.AccessControlBypass); ok {
		r0 = rf(rctx, now, limit)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]*model.AccessControlBypass)
	}
	if rf, ok := ret.Get(1).(func(request.CTX, int64, int) error); ok {
		r1 = rf(rctx, now, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *AccessControlBypassStore) Get(rctx request.CTX, id string) (*model.AccessControlBypass, error) {
	ret := _m.Called(rctx, id)

	var r0 *model.AccessControlBypass
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, string) *model.AccessControlBypass); ok {
		r0 = rf(rctx, id)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*model.AccessControlBypass)
	}
	if rf, ok := ret.Get(1).(func(request.CTX, string) error); ok {
		r1 = rf(rctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *AccessControlBypassStore) HasActive(rctx request.CTX, check model.AccessControlBypassActiveCheck) (bool, error) {
	ret := _m.Called(rctx, check)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, model.AccessControlBypassActiveCheck) bool); ok {
		r0 = rf(rctx, check)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if rf, ok := ret.Get(1).(func(request.CTX, model.AccessControlBypassActiveCheck) error); ok {
		r1 = rf(rctx, check)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *AccessControlBypassStore) MarkAccepted(rctx request.CTX, id string, acceptedAt int64, joinedAt int64, membershipCreated bool) (*model.AccessControlBypass, error) {
	ret := _m.Called(rctx, id, acceptedAt, joinedAt, membershipCreated)

	var r0 *model.AccessControlBypass
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, string, int64, int64, bool) *model.AccessControlBypass); ok {
		r0 = rf(rctx, id, acceptedAt, joinedAt, membershipCreated)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*model.AccessControlBypass)
	}
	if rf, ok := ret.Get(1).(func(request.CTX, string, int64, int64, bool) error); ok {
		r1 = rf(rctx, id, acceptedAt, joinedAt, membershipCreated)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *AccessControlBypassStore) Revoke(rctx request.CTX, id string, deleteAt int64, deletedBy string) (*model.AccessControlBypass, error) {
	ret := _m.Called(rctx, id, deleteAt, deletedBy)

	var r0 *model.AccessControlBypass
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, string, int64, string) *model.AccessControlBypass); ok {
		r0 = rf(rctx, id, deleteAt, deletedBy)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*model.AccessControlBypass)
	}
	if rf, ok := ret.Get(1).(func(request.CTX, string, int64, string) error); ok {
		r1 = rf(rctx, id, deleteAt, deletedBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *AccessControlBypassStore) Save(rctx request.CTX, bypasses []*model.AccessControlBypass) ([]*model.AccessControlBypass, error) {
	ret := _m.Called(rctx, bypasses)

	var r0 []*model.AccessControlBypass
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, []*model.AccessControlBypass) []*model.AccessControlBypass); ok {
		r0 = rf(rctx, bypasses)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]*model.AccessControlBypass)
	}
	if rf, ok := ret.Get(1).(func(request.CTX, []*model.AccessControlBypass) error); ok {
		r1 = rf(rctx, bypasses)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *AccessControlBypassStore) Search(rctx request.CTX, opts model.AccessControlBypassSearch) ([]*model.AccessControlBypass, int64, error) {
	ret := _m.Called(rctx, opts)

	var r0 []*model.AccessControlBypass
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(request.CTX, model.AccessControlBypassSearch) []*model.AccessControlBypass); ok {
		r0 = rf(rctx, opts)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]*model.AccessControlBypass)
	}
	if rf, ok := ret.Get(1).(func(request.CTX, model.AccessControlBypassSearch) int64); ok {
		r1 = rf(rctx, opts)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if rf, ok := ret.Get(2).(func(request.CTX, model.AccessControlBypassSearch) error); ok {
		r2 = rf(rctx, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
